Documentation
PyCubed-Mini/RexDB pull request #11
Opened 2023-05-30 13:43 UTC by tomyyyD

Documentation in a README.md as there are only 4 functions to be documented at the moment.

2023-05-30 19:51 UTC, tomyyyD commented
also removes the cursor input for rexDB as it is not needed any longer.

2023-06-08 03:52 UTC, thetazero requested changes

2023-06-08 03:52 UTC, thetazero commented on README.md
> +rexDB works in a very straightforward manner. It works through the operating system file structure. The database is stored in a directory called db\_\<number\>, this is so that multiple databases cou
capital R

2023-06-08 03:52 UTC, thetazero commented on README.md
> +## Methods
There should be a way to auto generate these docs, which is more convenient.
Although given that you have already done this, probably not worth it.

2023-06-08 03:53 UTC, thetazero commented
The high level overview seems great

2023-06-17 22:20 UTC, thetazero approved these changes

2023-06-21 18:15 UTC, merged